### ISSUE TITLE
IO naming conflict with Io programming language

### ISSUE THREAD

**Issue by timhudson** [node-forward/discussions#19]
> ... there is already a programming language named "Io", whose binary is named "io".

This issue was raised in https://github.com/iojs/io.js/issues/37#issuecomment-65495634 and probably warrants it's own discussion.

https://github.com/stevedekorte/io
http://iolanguage.org/

There has been some [discussion](https://github.com/iojs/io.js/issues/43) about using a `iojs` binary instead of `io` so that shouldn't be a problem. I do want to hear how people feel about the conflict in project name though. Is io.js distinct enough from Io?

We should be very considerate of Io and include them in this discussion if we are going to start broadcasting io.js.

**Comment by aearly** [comment]
The proposed `iojs` binary name should prevent any ambiguity with the `io` interpreter.

At a higher level, Io is a language, and io.js is a Javascript platform.  Seems distinct enough, especially if it will be always referred to as "io **.js** ". 

Some of the proposed io.js logos involve the Galilean moon as a theme, but it's unclear as to whether the Io language is named after the moon, the Roman pantheon god, or something else entirely.  Not sure if there is a conflict there.

Ultimately, it would be best if @stevedekorte weighed in.

**Comment by tolmasky** [comment]
With regard to the not-coolness, the reality is that if io is chosen then it will probably make the existing io community's life harder (regardless of the language/platform split), due to the sheer size of the javascript community. I imagine searching for io (lang) related things won't be too fun. (I suppose a counter argument is that this may already be the case just with general i/o as a term -- that might actually be another reason to potentially name this fork something different: "io packages" is going to be pretty crowded search space)

**Comment by stevedekorte** [comment]
fwiw, I think "io" in the input/output sense has precedence over the Io language so if "iojs" is being used in the sense of an i/o library, that seems fine. If it's a new name for a node fork which sort of gets into the language/devenv territory, then yes, something other  io" or "iojs" would make sense to me to avoid confusion. In any case, I feel you should do whatever feels right to you and I only have good vibes towards your project either way  :)

**Comment by rmg** [comment]
It would be nice if the TC could come out with some sort of official statement about the name being "iojs" so people stop shortening it to "io" (the moon? the programming language?) or writing it as "io.js" (a JS port of the _other_ prototype based language?)

Or maybe someone should implement an io vm in JS named io.js to force the issue?

**Comment by AlgoTrader** [comment]
Ubuntu has "node" executable that is anything but node.js. Node.js there is "nodejs", I have to install 'sudo apt-get install nodejs-legacy' to nave 'native' node from command prompt.

io.js is bad name. js means extension and io is expected to be a JS source file. iojs seems to be reasonable for all platforms

**Comment by rlidwka** [comment]
> io.js is bad name. js means extension and io is expected to be a JS source file.

Project name: "io.js"
Binary name: "iojs"

We're talking about project name here. They do not have extensions.

**Comment by sonewman** [comment]
could we not just add an option to ./configure to define the binary name, that way it can easily be installed under whatever name the user wants

**Comment by scottsword** [comment]
I never hear users of node call it "node js" or the worse "node dot js". By and large people simply call Node.js "node". I'm actually kind of bummed the ".js" rubbish got pulled over to io. So I agree with rlidwka, its an extension, not a project.

**Comment by mikeal** [comment]
@maxogden calls it “node point javascript"

**Comment by timkuijsten** [comment]
@scottsword I often call it "node js"

**Comment by Fishrock123** [comment]
http://logs.libuv.org/node-forward/2014-11-24#21:13:43.248

I had originally intended it to be "io dot js" aka "input / output (dot) javascript" aka "a library / file / platform for Javascript I/O" - hence the name as if it were a javascript file - io.js

.. but it also is cool to think of it as a moon or anything else too.

Whatever, I'll take the blame; just my two cents. I don't care _too_ much so long as we are actually making progress.
