### ISSUE TITLE
Please include OpenBSD in the automated build/test environment.

### ISSUE THREAD

**Issue by qbit** [node-forward/discussions#20]
As it is currently, (a few months ago?) OpenBSD misses out on automated build processes. It would be great if this could be added early on as to help catch bugs :D

I offer up my services to maintain the machine(s) if that will help!

Signed,
The OpenBSD node.js port maintainer.

**Comment by kenany** [comment]
An issue for [`iojs/build`](https://github.com/iojs/build)?

**Comment by bnoordhuis** [comment]
@qbit What @KenanY said, iojs/build is the best place for that.  I'll go ahead and close this issue.

I'd be okay with adding openbsd to the CI but some discussion on specifics is probably in order.
